### ISSUE TITLE
Can't figure out syntax for Array#select

### ISSUE THREAD

**Issue by asilano** [cyoce/J-uby#1]
This might be a user-incompetence issue, or maybe it could do with being added to the docs.

Suppose I want a program that takes an array and returns an array of the even values from the input - that is, I want `->a{a.select(&:even?)}`. I can't figure the right syntax for this. 

My best attempt, `ruby func.rb -e "~:select&:even?" "[1,2,3]"`, produces the error:

```
func.rb:165:in `select': wrong number of arguments(1 for 0) (ArgumentError)
        from func.rb:165:in `call'
        from func.rb:165:in `call'
        from func.rb:67:in `block in ~'
        from func.rb:33:in `call'
        from func.rb:33:in `block in &'
        from func.rb:285:in `call'
        from func.rb:285:in `block in <main>'
        from func.rb:235:in `on'
        from func.rb:283:in `<main>'
```

**Comment by ConorOBrien-Foxx** [comment]
What you probably want is `:select.& &:even?`

**Comment by asilano** [comment]
Meaning "curry `:select` with the _proc_ `:even?`"? O...kay. Yes, I guess that makes sense. Do we drop the `~` because the block param isn't positional?

Any idea why `:select& &:even?` doesn't work? Must be something arcane in the parser, but I don't know what.

**Comment by ConorOBrien-Foxx** [comment]
No idea why that doesn't work, sorry

**Comment by cyoce** [comment]
That doesn't work because `&` is an operator that expects two arguments (by
convention), so there's no reason any reasonable ruby object would require
calling an operator with a block so we have to use the method syntax `.&`

**Comment by asilano** [comment]
All right, makes sense. So this issue has an actual point, can I request that the ReadMe get updated with an example like this, where a proc needs a block? I don't know if it's worth an example where the block isn't a simple predicate, or if that works against what J-uby is designed to do.

**Comment by cyoce** [comment]
Just noticed this many months later (whoops). I have now implemented `#+`  in such a way that you can now just do `:select+:even?` instead of `select.& &:even?` (or even `select.&(&:even?) in the frequent case where you have operations before the `select`). Helps with precedence, byte count. and confusion.
